# .dbt/profiles.yml  (for CI only)
aw_sqlserver:
  target: ci
  outputs:
    ci:
      # CI uses DuckDB in-memory: no secrets, no drivers, no SQL Server.
      type: duckdb
      path: ":memory:"
      schema: main